# Generated by Django 4.1.3 on 2023-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.TextField(default='empty'),
        ),
    ]
