-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 15:01:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Status` TINYINT(4) NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `idFaculty` INT NOT NULL AUTO_INCREMENT,
  `FacultyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFaculty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `Faculty_idFaculty` INT NOT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `fk_Department_Faculty1_idx` (`Faculty_idFaculty` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Faculty1`
    FOREIGN KEY (`Faculty_idFaculty`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TeacherTitle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TeacherTitle` (
  `idTeacherTitle` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Department_idDepartment` INT NOT NULL,
  PRIMARY KEY (`idTeacherTitle`),
  INDEX `fk_TeacherTitle_Department1_idx` (`Department_idDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_TeacherTitle_Department1`
    FOREIGN KEY (`Department_idDepartment`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `idTeacher` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Status` TINYINT(4) NULL,
  `Faculty_idFaculty` INT NOT NULL,
  `TeacherTitle_idTeacherTitle` INT NOT NULL,
  PRIMARY KEY (`idTeacher`),
  INDEX `fk_Teacher_Faculty1_idx` (`Faculty_idFaculty` ASC) VISIBLE,
  INDEX `fk_Teacher_TeacherTitle1_idx` (`TeacherTitle_idTeacherTitle` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Faculty1`
    FOREIGN KEY (`Faculty_idFaculty`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_TeacherTitle1`
    FOREIGN KEY (`TeacherTitle_idTeacherTitle`)
    REFERENCES `mydb`.`TeacherTitle` (`idTeacherTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LessonSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LessonSchedule` (
  `idLessonSchedule` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idLessonSchedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grades` (
  `idGrades` INT NOT NULL AUTO_INCREMENT,
  `QuizGrade` TINYINT NULL,
  `HWGrade` TINYINT NULL,
  `MidtermGrade` TINYINT NULL,
  `FinalGrade` TINYINT NULL,
  `Attendence` TINYINT NULL,
  `EnterDate` DATETIME NULL,
  PRIMARY KEY (`idGrades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `BirthDate` YEAR NOT NULL,
  `Class` TINYINT(4) NOT NULL,
  `Status` TINYINT(4) NULL,
  `LessonSchedule_idLessonSchedule` INT NOT NULL,
  `Grades_idGrades` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_Student_LessonSchedule1_idx` (`LessonSchedule_idLessonSchedule` ASC) VISIBLE,
  INDEX `fk_Student_Grades1_idx` (`Grades_idGrades` ASC) VISIBLE,
  CONSTRAINT `fk_Student_LessonSchedule1`
    FOREIGN KEY (`LessonSchedule_idLessonSchedule`)
    REFERENCES `mydb`.`LessonSchedule` (`idLessonSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Grades1`
    FOREIGN KEY (`Grades_idGrades`)
    REFERENCES `mydb`.`Grades` (`idGrades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `Type` TINYINT(4) NOT NULL,
  `Text` TEXT(255) NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Teacher_idTeacher` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idAddress`, `Admin_idAdmin`, `Teacher_idTeacher`, `Student_idStudent`),
  INDEX `fk_Address_Admin_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Address_Teacher1_idx` (`Teacher_idTeacher` ASC) VISIBLE,
  INDEX `fk_Address_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Admin`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `mydb`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lesson` (
  `idLesson` INT NOT NULL AUTO_INCREMENT,
  `LessonName` VARCHAR(45) NOT NULL,
  `Department_idDepartment` INT NOT NULL,
  `Grades_idGrades` INT NOT NULL,
  PRIMARY KEY (`idLesson`),
  INDEX `fk_Lesson_Department1_idx` (`Department_idDepartment` ASC) VISIBLE,
  INDEX `fk_Lesson_Grades1_idx` (`Grades_idGrades` ASC) VISIBLE,
  CONSTRAINT `fk_Lesson_Department1`
    FOREIGN KEY (`Department_idDepartment`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lesson_Grades1`
    FOREIGN KEY (`Grades_idGrades`)
    REFERENCES `mydb`.`Grades` (`idGrades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LessonSchedule_has_Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LessonSchedule_has_Lesson` (
  `LessonSchedule_idLessonSchedule` INT NOT NULL,
  `Lesson_idLesson` INT NOT NULL,
  PRIMARY KEY (`LessonSchedule_idLessonSchedule`, `Lesson_idLesson`),
  INDEX `fk_LessonSchedule_has_Lesson_Lesson1_idx` (`Lesson_idLesson` ASC) VISIBLE,
  INDEX `fk_LessonSchedule_has_Lesson_LessonSchedule1_idx` (`LessonSchedule_idLessonSchedule` ASC) VISIBLE,
  CONSTRAINT `fk_LessonSchedule_has_Lesson_LessonSchedule1`
    FOREIGN KEY (`LessonSchedule_idLessonSchedule`)
    REFERENCES `mydb`.`LessonSchedule` (`idLessonSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LessonSchedule_has_Lesson_Lesson1`
    FOREIGN KEY (`Lesson_idLesson`)
    REFERENCES `mydb`.`Lesson` (`idLesson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
